### ISSUE TITLE
BITCOIN CASH

### ISSUE THREAD

**Issue by example34** [allienworks/cryptocoins#104]
To request icons for your coin, please fill info below:

---

### Coin name (`BCC`)

* link to logo: http://i.imgur.com/67R21dX.png
* official website: https://www.bitcoincash.org/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
- https://github.com/allienworks/cryptocoins/blob/master/SVG/BCH.svg
- https://github.com/allienworks/cryptocoins/blob/master/SVG/BCH-alt.svg
