### ISSUE TITLE
npm package doesn't contain BCH, please release a new version to npm

### ISSUE THREAD

**Issue by clarkorz** [allienworks/cryptocoins#107]
BCC(Bitcoin Cash) has been rename to BCH. This change has been committed a month ago. But npm package still using BCC. Could you release a new version to npm? thanks.

**Comment by pointtoken** [comment]
Agree - We want to keep using NPM for versioning and simplicity but we want the latest goodness!

**Comment by allienworks** [comment]
Done, new version released.

**Comment by pointtoken** [comment]
thanks!
