### ISSUE TITLE
IOTA

### ISSUE THREAD

**Issue by mvdenk** [allienworks/cryptocoins#108]
### Coin name (`IOTA`)

* link to logo: https://steemit-production-imageproxy-upload.s3.amazonaws.com/DQmam8GMxesngXyctGAx8pEVM1wGU6dFck6xSHfPnCu6Ain
* official website: https://iota.org/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#ffffff`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1216479.0

**Comment by allienworks** [comment]
Already done:

- https://github.com/allienworks/cryptocoins/blob/master/SVG/IOTA.svg
- https://github.com/allienworks/cryptocoins/blob/master/SVG/IOTA-alt.svg
