### ISSUE TITLE
Request for EMC2

### ISSUE THREAD

**Issue by klappy** [AllienWorks/cryptocoins#113]
To request icons for your coin, please fill info below:

I'm not related to this project in any way other than building an app that uses the icons and needing an icon for Einsteinium. 
I'm using `react-cryptocoins` library, but since it gets the icons from this project, I'm requesting upstream first.
https://github.com/kirillshevch/react-cryptocoins

Thanks in advance!
Also, what's a good donation/tip to support your efforts and speed up the addition?

---

### EINSTEINIUM (`EMC2`)

* link to logo: https://static1.squarespace.com/static/5899c98cbe65949bde4ac188/t/58a230fc440243e6ccd4137d/1512506320988/?format=1500w
* official website: https://www.emc2.foundation/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hi @klappy, thanks for input. Requesting icons here "upstream" is absolutely fine. Various donation addresses are [listed on my website]() – if you can't find your fav coin there, let me know, I'll send you the address (I don't list all the coins I use, that would be a long list :)

However I have to warn you, I have very little time on my hands now, so I'm not sure when I'll be able to process this and other new icon requests. Might be even next year, sorry.
