### ISSUE TITLE
Bitcoin Gold (BTG)

### ISSUE THREAD

**Issue by SerhanKarakaya** [AllienWorks/cryptocoins#114]
Bitcoin Gold (BTG)

* link to logo: https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-logo0k.png
* official website: https://bitcoingold.org

* logo color (HEX): `#eba809`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=2171754

**Comment by FerdiCildiz** [comment]
.SVG file is attached please update this. [bitcoingold.svg.zip](https://github.com/allienworks/cryptocoins/files/1551948/bitcoingold.svg.zip)

**Comment by Ashok-Varma** [comment]
@allienworks 
> now btg top 20 alt coin, i think this is really necessary

**Comment by gauravagarwal2704** [comment]
Can you please confirm, when BTG will be added ?

**Comment by allienworks** [comment]
> @gauravagarwal2704 Can you please confirm, when BTG will be added ?

No, I can't, sorry.

**Comment by adi-darachi** [comment]
:{
