### ISSUE TITLE
add svg icons with fullName version

### ISSUE THREAD

**Issue by fsanano** [allienworks/cryptocoins#117]

**Comment by allienworks** [comment]
What is that, what do you mean?

**Comment by fsanano** [comment]
Now all .svg files named with coin short version (BTC.svg etc). 
But can you add directory in SVG with full version- bitcoin.svg etc

**Comment by allienworks** [comment]
I don't think that is necessary. Everyone who knows/uses some coin knows its ticker symbol. There's no really need to have all icons 2× in the same repo.
