### ISSUE TITLE
BitcoinZ

### ISSUE THREAD

**Issue by imtase** [allienworks/cryptocoins#120]
### BitcoinZ (BTCZ)  

* link to logo: https://bitcoinz.global/media/bitcoinz_btcz_logos.zip
* official website: https://bitcoinz.global

Optional info:  

* logo color (HEX): `#f8c24a`, `#f8e565`, `#ffa700` (main)  `#42abcc` (Z color)
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=2166510.0

**Comment by allienworks** [comment]
I don't think I'll add a coin 3 months old. Many of those die out shortly. Re-submit this coin later and we'll see. Thanks!
