### ISSUE TITLE
Request to add VeChain (VEN)

### ISSUE THREAD

**Issue by Jasonkoolman** [AllienWorks/cryptocoins#140]
To request icons for your coin, please fill info below:

---

### VeChain (VEN)

* link to logo: https://files.coinmarketcap.com/static/img/coins/128x128/vechain.png
* official website: https://www.vechain.com/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#15BDFF`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by eddieadams** [comment]
Check https://bitonics.net/

**Comment by allienworks** [comment]
> @eddieadams Check https://bitonics.net/

Are you the author of Bitconics?

**Comment by eddieadams** [comment]
No just shilling. They state 236 icons in total. How many here?

**Comment by allienworks** [comment]
Currently 282. I'd love to have a word with Bitonics author though, as (s)he obviously taken Cryptocoins icons and just added some more, without giving me and other contributors proper credit. I have no problem with others reusing & remixing Cryptocoins, but this is not nice at all.

**Comment by eddieadams** [comment]
282... that means a total of 141 unique icons... They probably have another source.

**Comment by allienworks** [comment]
Sure.. here's [our Lisk](https://github.com/allienworks/cryptocoins/blob/master/SVG/LSK.svg) icon, here's [Bitonics' one](https://i.imgur.com/FpD10cO.png). Isn't that quite lucky? :)

But let's keep this issue on topic please.
