### ISSUE TITLE
Request to add BlackCoin

### ISSUE THREAD

**Issue by cryptoeax** [allienworks/cryptocoins#143]
### Coin name (`BLK`)

* link to logo: https://blackcoin.co/assets/images/hero/ag2-logo.png
* official website: https://blackcoin.co/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#393838`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=469640.0

**Comment by allienworks** [comment]
Already added.

- https://github.com/allienworks/cryptocoins/blob/master/SVG/BC.svg
- https://github.com/allienworks/cryptocoins/blob/master/SVG/BC-alt.svg

**Comment by cryptoeax** [comment]
Thank you!

**Comment by allienworks** [comment]
Your welcome!
