### ISSUE TITLE
Request to add SiaCoin

### ISSUE THREAD

**Issue by cryptoeax** [allienworks/cryptocoins#144]
### Coin name (`SC`)

* link to logo: https://sia.tech/img/svg/sia-green-logo.svg
* official website: https://sia.tech/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#00C898`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1060294.0

**Comment by allienworks** [comment]
Already added.

- https://github.com/allienworks/cryptocoins/blob/master/SVG/SIA.svg
- https://github.com/allienworks/cryptocoins/blob/master/SVG/SIA-alt.svg

**Comment by cryptoeax** [comment]
Thank you, sorry I missed it!
