### ISSUE TITLE
Request to add - STELLAR (XLM)

### ISSUE THREAD

**Issue by gauravagarwal2704** [allienworks/cryptocoins#147]
To request icons for your coin, please fill info below:

---

### Coin name (`STELLAR`)

* link to logo: https://www.stellar.org/about/press/
* official website: https://www.stellar.org/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Already added: [STR](https://github.com/allienworks/cryptocoins/blob/master/SVG/STR.svg), [STR-alt](https://github.com/allienworks/cryptocoins/blob/master/SVG/STR-alt.svg)

**Comment by gauravagarwal2704** [comment]
But, the symbol for stellar is **XLM**

**Comment by allienworks** [comment]
Then the issue isn't about creating new icons, but about renaming existing ones. That's a difference.

Also check if existing issue isn't already created. This is a duplicate of https://github.com/allienworks/cryptocoins/issues/121

**Comment by gauravagarwal2704** [comment]
okay, my bad :) 
Will keep that in mind next time. Apologies.
