### ISSUE TITLE
Bitcoin Gold (BTG) 

### ISSUE THREAD

**Issue by gauravagarwal2704** [allienworks/cryptocoins#151]
To request icons for your coin, please fill info below:

---
I have checked previous issues, but seems like BTG has not yet merged into package. Can you please add it ?
P.S. - I am using **react-cryptocoins**

Duplicate of #114 

### Coin name (`TICKER`)

* link to logo: 
* official website: 

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
If you know that this is a duplicate, why do you create a new issue and don't respond in the original issue?
