### ISSUE TITLE
Coinmarketcap Top 25 Coins

### ISSUE THREAD

**Issue by nomivore** [allienworks/cryptocoins#152]
Would you be able to add the top 25 coins on coinmarketcap? Most of them are there it's just missing a few. I'd be willing to donate if you can get those done, and support you to get the top 50! Thanks.

I can request individually if that would help?

**Comment by allienworks** [comment]
Yes please, create individual Issues/requests _if_ they're not exsiting already. I have quite a lot on my hands now, the TODO is getting bigger and bigger :)
