### ISSUE TITLE
New coin

### ISSUE THREAD

**Issue by nisi1t** [AllienWorks/cryptocoins#167]
To request icons for your coin, please fill info below:

---

### Coin name (`TICKER`)
Electroneum / ETN

* link to logo: ???
* official website: https://electroneum.com/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by AllienWorks** [comment]
Duplicate of https://github.com/AllienWorks/cryptocoins/issues/146
