### ISSUE TITLE
Minified CSS files for webfont

### ISSUE THREAD

**Issue by webmasterslava** [AllienWorks/cryptocoins#170]
Please add minified CSS files for webfont:
webfont/cryptocoins.min.css
webfont/cryptocoins-colors.min.css

I could minify these files myself using webpack, but I'm loading them from https://cdn.jsdelivr.net to descrease my entry filesize.

**Comment by FastTrackBeginner** [comment]
Einverstanden


webmasterslava <notifications@github.com> schrieb am Fr., 11. Mai 2018,
18:52:

**Comment by MartinKolarik** [comment]
jsDelivr is able to minify the files on its own, just add `.min` to the filename:
https://cdn.jsdelivr.net/npm/cryptocoins-icons@2.7.0/webfont/cryptocoins.min.css
https://cdn.jsdelivr.net/npm/cryptocoins-icons@2.7.0/webfont/cryptocoins-colors.min.css
