### ISSUE TITLE
Rise : Logo Conversion

### ISSUE THREAD

**Issue by TheAlty** [allienworks/cryptocoins#18]
Please convert our Rise logo to your format so we can have it respresented in the Bittrex re-look!

Logo: https://s3.amazonaws.com/uploads.hipchat.com/576795/3922994/wTv8uQKjvx9FMnF/logo..png

Bitcointalk Thread: https://bitcointalk.org/index.php?topic=1445947.0

Rise Forum: http://forum.rise.vision/

**Comment by allienworks** [comment]
Hey @TheAlty!
New update was released containing RISE. Enjoy ;)
Tips appreaciated - RISE: `15561067220036225279R`
Cheers!
