### ISSUE TITLE
Please Add SIKKE

### ISSUE THREAD

**Issue by ersanmercanoglu** [AllienWorks/cryptocoins#182]
To request icons for your coin, please fill info below:

---

### SIKKE (`https://www.parifix.com/`)

* link to logo: https://www.sikke.com.tr/img/kurumsal/sikke-amblem-logo.png
* official website: https://www.sikke.com.tr/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#ff5500`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=3031316.0

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by ersanmercanoglu** [comment]
@AllienWorks

**Comment by ersanmercanoglu** [comment]
@wouterds  @yeahoffline @bradrisse @emilkarl @AllienWorks

**Comment by AllienWorks** [comment]
@ersanmercanoglu the spamming doesn't help at all if you wonder.. Same as creating duplicate issues.

**Comment by ersanmercanoglu** [comment]
can anyone do it for me? I will make donation... Cause i need it urgently...
