### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by valitnon** [AllienWorks/cryptocoins#187]
[This package](https://www.jsdelivr.com/package/npm/cryptocoins-icons) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by AllienWorks** [comment]
This doesn't really makes sense in this repo. Anybody's free to link to whatever files they want (be it either complete webfont version or just concrete SVG files..).
