### ISSUE TITLE
Augur (REP)

### ISSUE THREAD

**Issue by beylerian** [allienworks/cryptocoins#19]
Hello if possible, please consider adding Augur

https://sale.augur.net/

https://sale.augur.net/images/augur_logo_600.png

**Comment by allienworks** [comment]
Hey @beylerian, new release is out, this update included. Thanks for info and enjoy!

**Comment by vanlooverenkoen** [comment]
You said it was added but I can't find it anywhere in the ttf files from your website. please add to your ttf font on your website
