### ISSUE TITLE
Colored Coins

### ISSUE THREAD

**Issue by Sicria** [allienworks/cryptocoins#2]
Hi, great job so far, everything is looking great.

Could you possibly include an extra class option for colored coins, so like `.cc-c-BTC` or even something like `.ccc-BTC` currently I've just manually added colors for a few of the coins but it would be nice if there was an extra style sheet I could drop in that has it already done.

Also could you use 
```
.cc {

}
```
when you setup the font family so it does not conflict with anything.

**Comment by allienworks** [comment]
Hey, sorry it took so long, but I finally released 1.2.1 with colored icons (all of them). Thanks!
