### ISSUE TITLE
Auroracoin Request

### ISSUE THREAD

**Issue by SkateFish** [allienworks/cryptocoins#20]
Could you please add Auroracoin ?  

You can find the image at auroracoin.is - and I have attached it here. 

![aur_symbol](https://cloud.githubusercontent.com/assets/6824337/19235711/de863070-8ee2-11e6-9e2d-a4a69265cb3a.png)

**Comment by allienworks** [comment]
Could you please add coin ticker symbol as well?
I'll add this in next release, however I'm not sure when it will be.

Thanks for input!

**Comment by SkateFish** [comment]
Great !   Whatever I can do to help.   Put up an Auroracoin Address and I
will send some personal coins to you.

Mikjáll Hannes

ps.  wanna see a nice documentary ?

motherboard.vice.com/read/auroracoin
<http://motherboard.vice.com/read/auroracoin>

**Comment by SkateFish** [comment]
Coin Ticker Symbol ?

AUR   is the 3 letter code for Auroracoin on the exchanges, etc...

**Comment by allienworks** [comment]
Thanks @SkateFish for info. I'll check the documentary later, thanks for sharing!

And here's my AUR addy: `ANGpXsA2LeMwsKnt7U11VEmiL45LLLofne` – appreciate your donations; they keep me going :)

**Comment by SkateFish** [comment]
sent 20 - consider as a down payment.

**Comment by SkateFish** [comment]
sent you another 100 AUR.

We are planning on using that font for a WooCommerce site we are launching
soon.

mikki

**Comment by allienworks** [comment]
Hey @SkateFish, new release is out, this update included. I'm insanely sorry it took so long. Life was crazy lately. Hope it's all good :)

Cheers and thanks!
