### ISSUE TITLE
Adding Blockfreight™ [BFT:XCP] token

### ISSUE THREAD

**Issue by jsmith-dev** [allienworks/cryptocoins#21]
Hi Martin,

As per your Tweet-back - i'll open a ticket and provide a request.
1. Name: Blockfreight™
2. Ticker: [BFT:XCP]
3. Sources: https://github.com/blockfreight/brandmarks
4. Direct File LINK: https://github.com/blockfreight/brandmarks/blob/master/bftxcp.svg

Sending feedback via Twitter.

**Comment by allienworks** [comment]
Thanks @jsmith-dev for a submission! I could do an example of this one, thanks for including everything all-in :) Blockfreight will be added in next update (not sure when that will be as I've just released one).

Take care!
Martin

**Comment by jsmith-dev** [comment]
That's awesome. Can't wait to see it and use it.

**Comment by allienworks** [comment]
Hey @jsmith-dev, new release is out, this update included. Thanks for info and enjoy!

**Comment by jsmith-dev** [comment]
Martin.. Thank you. It's great to be added to the collection!
