### ISSUE TITLE
Emerald Crypto (EMD)

### ISSUE THREAD

**Issue by pazor** [allienworks/cryptocoins#22]
Could you please add Emerald Crypto? 
Current logo here: http://www.pagezo.de:8082/emeraldcrypto/index.php?cat=Home&file=logo_128x128.png 

thank you very much ;)

PaZor
www.emeraldcrypto.de
info@emeraldcrypto.de

**Comment by allienworks** [comment]
Hi @Pazor,

thanks for your input. However I'm not sure how to draw this EMD logo..
I've done this already with https://github.com/allienworks/cryptocoins/blob/master/SVG/DMD-alt.svg and EMD looks like the same.

Is this the only logo you have? Any other idea how to solve this?

**Comment by allienworks** [comment]
_Stalled development_
