### ISSUE TITLE
NEOS update

### ISSUE THREAD

**Issue by Stoner19** [allienworks/cryptocoins#27]
NeosCoin has gotten an update to their logo. Would you please update it? 

http://i.imgur.com/7QiP5Ci.png

Thank you!

**Comment by buzztiaan** [comment]
i'm totally looking for allienworks' work to make this a monochrome logo, i hope it will be possible

**Comment by allienworks** [comment]
Well anything can be monochrome.. it just depends if it will look well.

Thanks for this update @Stoner19!

**Comment by buzztiaan** [comment]
we (designer of that logo and me) had some discussion on twitter about it ; 

https://twitter.com/kalipodesign/status/837757310965547012

he might have something usuable for you soon

**Comment by allienworks** [comment]
Thanks @buzztiaan, I'll probably go that way.

**Comment by buzztiaan** [comment]
i need it myself, for this : 

![image](https://cloud.githubusercontent.com/assets/940336/23676186/280af646-037c-11e7-84ff-e1386df5420e.png)

**Comment by allienworks** [comment]
New release is out, this update included. Enjoy your HW beast @buzztiaan and cheers @Stoner19!
