### ISSUE TITLE
ICN (Iconomi)

### ISSUE THREAD

**Issue by githubacc32** [allienworks/cryptocoins#29]
Hi,

requesting to add Iconomi (ICN).
Logo: https://iconomi.net/assets/logos/logo-30ed55eb8048292e903f9a531a5e0fa75a3b3a21686c53e9d2338dfae180977f.svg
(maybe make it look like on their Twitter: https://twitter.com/iconominet)
Thread: https://bitcointalk.org/index.php?topic=1789926.0

Thank you.

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
