### ISSUE TITLE
KMD (Komodo)

### ISSUE THREAD

**Issue by githubacc32** [allienworks/cryptocoins#30]
Hi,

requesting to add Komodo (KMD).
Logo Pack: https://komodoplatform.com/downloads/Komodo_Branding_v1.0.rar
Branding Guide: https://komodoplatform.com/downloads/Komodo_Brand_guide_v0.pdf
Thread: https://bitcointalk.org/index.php?topic=1605144.0

Thank you.

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
