### ISSUE TITLE
DCT (Decent)

### ISSUE THREAD

**Issue by githubacc32** [allienworks/cryptocoins#31]
Hi,

requesting to add Decent (DCT).
Logo: https://decent.ch/img/logo.png
Thread: https://bitcointalk.org/index.php?topic=1162392.0

Thank you.

**Comment by allienworks** [comment]
Hi, looks like Decent isn't even released yet, so no icon for it so far. When it's out, I'll make it. You can notify me when that happens. Thanks.

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
