### ISSUE TITLE
HEAT (HEAT Ledger)

### ISSUE THREAD

**Issue by githubacc32** [allienworks/cryptocoins#32]
Hi,

requesting to add HEAT Ledger (HEAT).
Logo: http://i.imgur.com/Cr0v6zJ.png
Thread: https://bitcointalk.org/index.php?topic=1543991.0

Thank you.

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
