### ISSUE TITLE
INCNT (Incent)

### ISSUE THREAD

**Issue by githubacc32** [allienworks/cryptocoins#33]
Hi,

requesting to add Incent (INCNT).
Logos:
1: https://static.wixstatic.com/media/3c35cd_91d685e6586441768d26c4fc56e77099~mv2.png/v1/fill/w_84,h_84,al_c,usm_0.66_1.00_0.01/3c35cd_91d685e6586441768d26c4fc56e77099~mv2.png
2: https://cdn-images-1.medium.com/max/800/1*8oOzZ9lHjt2_UtlS8MVslg.png
Thread: https://bitcointalk.org/index.php?topic=1610052.0

Thank you.

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
