### ISSUE TITLE
Triggers  $trig

### ISSUE THREAD

**Issue by blocksafe** [allienworks/cryptocoins#34]
To request icons for your coin, please fill info below:

---

### Triggers (`TRIG`)

* link to logo: http://blocksafefoundation.com/new.png
* official website: http://blocksafefoundation.com
https://coinmarketcap.com/assets/triggers/#markets

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1642159.msg18301326#msg18301326

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
