### ISSUE TITLE
(BRK) Could you please add Breakout Coin? Thx!!

### ISSUE THREAD

**Issue by Mario14Brk** [allienworks/cryptocoins#35]
To request icons for your coin, please fill info below:

---

### Breakout Coin (`BRK`)

* link to logo: http://www.breakoutcoin.com/wp-content/uploads/2016/01/logo_brk_head-1.png
* official website http://www.breakoutcoin.com/ 

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): sorry :( 
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1509819.msg15185942#msg15185942

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
