### ISSUE TITLE
Can you please add Breakout Stake? ty (BRX)

### ISSUE THREAD

**Issue by Mario14Brk** [allienworks/cryptocoins#36]
To request icons for your coin, please fill info below:

---

### Coin name (`BRX`)

* link to logo: https://www.dropbox.com/s/fhkbier5cj0wcos/brx.png?dl=0
* official website: http://www.breakoutcoin.com/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1509819.msg15185942#msg15185942

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
