### ISSUE TITLE
Ubiq (UBQ)

### ISSUE THREAD

**Issue by outragedhuman** [allienworks/cryptocoins#37]
To request icons for your coin, please fill info below:

---

### Ubiq (UBQ)

* link to logo: https://i.imgur.com/t58iSZO.png
* official website: https://ubiqsmart.com/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): #00ea90  #0ca579  #494949  #333333
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1763606.0

---

Would love it if you'd add UBQ, thank you so much! Let me know if you need anything else. 

**NOTE:** Please ensure full coin name is Ubiq and not UBIQ (there's another coin that stole the name once it was announced). Thanks again!

**Comment by outragedhuman** [comment]
Updated logo link to use a better URL.

**Comment by outragedhuman** [comment]
Not sure if this would help, but here's an SVG of the same logo as well :)

http://ubiqpool.io/ubiq.svg

**Comment by BitterLox** [comment]
You should also know ubiq is the result of a swap from jbs. Not saying JBS icons should be removed, having them for legacy use can always be handy.

**Comment by allienworks** [comment]
Hey guys, UBQ icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
