### ISSUE TITLE
"PIVX (PIVX)", description: "Could you please add PIVX?

### ISSUE THREAD

**Issue by PIVX-Project** [allienworks/cryptocoins#38]
Please add these icons to you set. :)

[PIVX-Icons.zip](https://github.com/allienworks/cryptocoins/files/872729/PIVX-Icons.zip)

To request icons for your coin, please fill info below:

---

### Coin name (`TICKER`)

* link to logo: 
* official website: 

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by PIVX-Project** [comment]
When will these be merged??

**Comment by allienworks** [comment]
When I have time to do so. Excuse me, but I'm very busy this month.

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
