### ISSUE TITLE
FLO (Florincoin)

### ISSUE THREAD

**Issue by metacoin** [allienworks/cryptocoins#39]
### FLO

* link to logo: 
We have a vector graphics version of the icon, you can find it here:
https://github.com/metacoin/florin-graphics/blob/master/FlorincoinVectorLogoShareVer.ai
We also have two different logos with different style Fleur-De-Lys:
https://github.com/metacoin/florin-graphics/blob/master/flo-blue-small-2.png
https://github.com/metacoin/florin-graphics/blob/master/FLORINONLY_Shadow_500px_DLVR.png

* official website: http://florincoin.org/
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=236742.0

**Comment by metacoin** [comment]
forgot to add logo colors:

#F6DE5C
#1358C8

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
