### ISSUE TITLE
GNT (Golem)

### ISSUE THREAD

**Issue by juanparadox** [allienworks/cryptocoins#41]
### Golem (GNT)

* link to logo:  https://2.bp.blogspot.com/-kmJc65bmFXU/WKtGvYRxRBI/AAAAAAAADVs/GYsDAYmBPV8vWedaQ9_BlezQ6b0BNbetACLcB/s1600/golem-512x512.png
* official website: https://golem.network/

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!

**Comment by vanlooverenkoen** [comment]
**You said it was added but I can't find it anywhere in the ttf files from your website. please add to your website**
