### ISSUE TITLE
PepeCoin ('PEPE')

### ISSUE THREAD

**Issue by casinobitcoin** [allienworks/cryptocoins#43]
### PepeCoin ('PEPE')

* link to logo: https://ip.bitcointalk.org/?u=http%3A%2F%2Fi.imgur.com%2FhDXKtDB.png&t=576&c=kz5MzniQUsctcw
* official website: N/A

**Optional info** (not mandatory, but saves me time):

* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1391598

---
Shoot me a note on admin@bitcoinrush.io, I'll give you a donation in btc

**Comment by allienworks** [comment]
OK, honestly – I have no idea how to transform this crazy logo into black/white vector icon. So until you want me to add the [other one](https://ip.bitcointalk.org/?u=http%3A%2F%2Fi.imgur.com%2Fhpkr1b6.png&t=576&c=ZosSbih74X2oZg), I think I can't add it. Sorry.

**Comment by casinobitcoin** [comment]
Martin - That's totally fine, let's go with the other logo!

**Comment by allienworks** [comment]
OK, so to be clear: the other logo, "PepeCoin" name and "PEPE" ticker? Or are you using different name/ticker for the other logo? (I think I read something like that on your BTCT thread.)

**Comment by casinobitcoin** [comment]
PepeCoin is correct, thanks Martin
