### ISSUE TITLE
Availability under different OSS license?

### ISSUE THREAD

**Issue by RichyHBM** [allienworks/cryptocoins#45]
Currently the font is only available under the GPL license, this is considered by some as a viral license and is rather restrictive.

I propose allowing the usage under additional licenses, for example using it under either GPL or something like the Apache 2.0 license.

MIT/ZLib/BSD/Apache are all quite open licenses, Apache 2.0 having the additional bonus of any modifications having to be merged back into the original source (so if anyone added icons or fixed any they would also have to merge them back into the main project)

**Comment by allienworks** [comment]
Hey @RichyHBM, thanks very much for your input! Personally, I'm in no way a licence pro, so I'm glad for your initiative. Honestly I haven't thought about GPL's "virality", but it makes sense.

> I propose allowing the usage under additional licenses, for example using it under either **GPL** or something like the Apache 2.0 license.

I guess there's a typo, right?

From what you write (and from what I've read on [Choose a licence](https://choosealicense.com/licenses/)), Apache 2.0 or MIT sounds the best. To make it clear: I don't really care about restrictions (as long as nobody will repackage it and sell it for millions), but attribution to the author and/or project page would be nice.

I'm open to a conversation. What would you suggest?

**Comment by RichyHBM** [comment]
Whoops, yes, that was indeed a typo!

Well, for my projects I quite like the Apache 2.0 license due to the fact you are supposed to report modifications, I'm also not an expert but my assumption means if a user were to find a bug and fix it, they would have to report the fix back into the main project. This may not be as necessary with a assets/content based project (as I assume most issues come from people wanting additions rather than finding issues with the existing icons)

The MIT license on the other hand provides what you ask, users need to credit you/include a license copy, and they can not sue you if your project somehow creates skynet 😆 

Here are some quick references of the licenses:
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
https://tldrlegal.com/license/mit-license

I guess if you aren't too worried about people having to report back with any "significant modifications" to the project, the MIT would be a nice choice!

Let me know if you make a choice, I would be more than happy to submit a PR with modifications 😄

**Comment by allienworks** [comment]
Thanks for the resources! So far MIT looks the best. Let me think about it a little longer..

If I were to change the licence, can I just swap the Licence file + the info in Readme or is there some more specific process of doing so?

**Comment by RichyHBM** [comment]
So, as far as github is concerned, yes you just swap the text in the license file & readme and GH should pick it up and update etc.

In terms of the technical terms of the licensing, I believe how it works is all the versions of the icon pack up until now would continue to be licensed under GPL, and any future versions (or direct download from github) would have the new license applied. But that is all based on assumptions, IANAL ;)

**Comment by RichyHBM** [comment]
Hey there @allienworks, any further thoughts on this?

**Comment by allienworks** [comment]
@RichyHBM Switched; thanks!

**Comment by RichyHBM** [comment]
Awesome! :D
