### ISSUE TITLE
Golos (GOLOS)

### ISSUE THREAD

**Issue by vanlooverenkoen** [allienworks/cryptocoins#48]
### Golos (GOLOS)

* link to logo: https://files.coinmarketcap.com/static/img/coins/32x32/golos.png
* official website: https://golos.io/

**Optional info** (not mandatory, but saves me time):

* logo color #4286f4:

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
