### ISSUE TITLE
ZCash Request

### ISSUE THREAD

**Issue by ASCIIcat** [allienworks/cryptocoins#53]
---

### Coin name (`ZEC`)

* link to logo: https://z.cash/theme/images/zcash-logo-black-small.png
* official website: https://z.cash/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#CB842A` (Seems to be the main colour that is used
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=1626185.0

---

**Comment by buzztiaan** [comment]
uh? https://github.com/allienworks/cryptocoins/blob/master/SVG/ZEC.svg 3 months old ..

**Comment by ASCIIcat** [comment]
My apologies I was coming from your site where you have the coins listed:
https://labs.allienworks.net/icons/cryptocoins/
