### ISSUE TITLE
Webfont, creating your own names characters differently...

### ISSUE THREAD

**Issue by foxinni** [allienworks/cryptocoins#55]
Hi,

So I tried to generate my own webfont but the character codes are all wrong now. Please keep generating webfonts if it's not a big deal. 

Or I'm doing something wrong...

M

**Comment by allienworks** [comment]
Can you provide more details (eg. screenshot of the problem)? I can't help you like this.

**Comment by foxinni** [comment]
It's simple really. The webfont you previously provided has the icon unicodes set a certain way. When I generate my own their previous values are lost. See the two screenshots with no change to the css from my side.

Old:
<img width="316" alt="0 00000660 sc_btc market - poloniex bitcoin_digital asset exchange" src="https://user-images.githubusercontent.com/124101/27291009-3e92e68c-550f-11e7-87c0-cc28ffe87332.png">

New
<img width="352" alt="new" src="https://user-images.githubusercontent.com/124101/27290986-26c15624-550f-11e7-825d-57424d69e564.png">

**Comment by allienworks** [comment]
OK, I see your problem. Do you realise that even if I generate the webfont myself, the outcome would be the same (= wrong)? I wasn't generating them by hand – I used the same technique [I wrote about and recommended](https://allien.work/blog/howto-generate-icon-webfont).

> ..with no change to the css from my side.

When you generate the webfont, you have to use the generated CSS as well! The CSS file contains info about which unicode character belongs to each icon. If you use "my" CSS (from my latest webfont release) but use *your* webfont files – yes, it will be mixed up. You always have to use both – the webfonts and CSS work in pairs with each other.

**Comment by foxinni** [comment]
Yeah. I realize that now. Maintenance would be a nightmare if I had to do it like that. The webfont is nice because of the single http request and colors. Let me try find a solution and get back to you.

**Comment by allienworks** [comment]
> Maintenance would be a nightmare if I had to do it like that.

Exactly. That's the reason I don't generate the webfonts with each update anymore.
