### ISSUE TITLE
SIA.svg is Broken

### ISSUE THREAD

**Issue by kazazor** [allienworks/cryptocoins#56]
This is happening when you're trying to parse the SVG over the browser / via `svgo`.

<img width="1018" alt="screen shot 2017-06-25 at 12 45 54 am" src="https://user-images.githubusercontent.com/1577655/27512152-abfc03f0-593f-11e7-8b1a-e850aecdf4b0.png">

**Comment by kazazor** [comment]
Just need to delete all the `sketch` parts:
```svg
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 226.8 226.8" style="enable-background:new 0 0 226.8 226.8;" xml:space="preserve">
<g id="Get-started">
	<g id="Desktop-_x28__x3E_1200px_x29_" transform="translate(-161.000000, -19.000000)">
		<g id="Nav" transform="translate(161.000000, 19.000000)">
			<g id="logo">
				<path id="Fill-2_1_" class="st0" d="M39.8,35.8c0.2,0.2,0.4,0.4,0.7,0.6L39.8,35.8C39.8,35.8,39.8,35.8,39.8,35.8"/>
				<path id="Fill-3_1_" class="st0" d="M43.8,31.9l0.6,0.6C44.2,32.3,44,32,43.8,31.9C43.8,31.8,43.8,31.9,43.8,31.9"/>
				<path id="Fill-4" class="st0" d="M191.4,88.3c-21.7-13.6-48.8-15-71.7-4.3c0,0,0,0,0,0c-12.1,5.5-26.7,3.5-37.1-5.8
					c-0.5-0.4-0.9-0.8-1.4-1.3l-46-46c0,0,0,0,0,0c-3.1-3.4-4.4-7.9-3.9-12.2c0,0,0,0,0,0c0.2-0.9,0.3-1.9,0.3-2.9
					C31.5,7,24.4,0,15.7,0S0,7.1,0,15.7c0,8.7,7,15.7,15.7,15.7c1,0,2-0.1,2.9-0.3c0,0,0,0,0,0C23,30.8,27.5,32,31,35c0,0,0,0,0,0
					l46.2,46.2c0.4,0.4,0.7,0.8,1,1.2c9.3,10.4,11.2,25,5.7,37.1c0,0,0,0,0,0c-10.8,22.8-9.4,50,4.3,71.7c2.9,4.7,6.4,9.1,10.4,13.1
					c12.9,12.9,30,20.5,46.9,22c4.4,0.4,67.4,0.2,67.4,0.2c3.4,0,6.9-1.7,9.3-4.1c2.4-2.4,4.4-6.3,4.4-9.7c0,0,0-58,0-61
					c0-3-0.7-7.4-0.7-8c-1.5-16.9-8.7-32.2-21.6-45.1C200.4,94.7,196,91.2,191.4,88.3L191.4,88.3z M195.4,139.4
					c1.8,8.7,1.9,12.5,1.9,13.1v30.9c0,3.4-1.5,7.4-3.9,9.8c-2.4,2.4-6.4,3.9-9.8,3.9h-30c-0.6,0-7.6-0.1-14.1-1.9
					c-7.3-2-14.1-5.9-19.8-11.6c-17.7-17.7-17.7-46.4,0-64.1c17.7-17.7,46.5-17.7,64.1,0C189.4,125.3,193.9,132,195.4,139.4
					L195.4,139.4z"/>
			</g>
		</g>
	</g>
</g>
</svg>
```

**Comment by kazazor** [comment]
IMO a good practice for this repo would be running `svgo` on a travis job.. Sounds easy enought o be done since you can use webpack and `svgo-loader` to try it out without any effort.. If the build fails one or more of the SVGs is broken

**Comment by allienworks** [comment]
Thanks for info, @kazazor! If some coin has its logo already in SVG, I include the original (if it's usable in small sizes – if not, I usually edit it a bit). This was one of those cases, I haven't checked the SVG, so thanks!

**Comment by kazazor** [comment]
No problem! :)

So what do you think in general on including svgo in your build process? So we won't find out of broken SVGs by the clients of the repo but way sooner than that..
At the moment that prevents me from using the package since I will not give up on `svgo` as part of my pipeline for serving SVGs

**Comment by allienworks** [comment]
I'm not sure how you think I _build_ SVGs other than in Illustrator/Inkscape :) This repo is pretty much just a collection of images. "Building" isn't really part of this process at all.. and I honestly don't have any experience with travis at all.

I'm open to suggestions/enlightenment though!

**Comment by kazazor** [comment]
What I'm saying it that you need a system that verifies you're not publishing SVGs that are broken **before** you publish a new version of the package.
At the moment this package is broken and we cannot use it.

My suggestion was to create a npm script to run `svgo` on all of your files. If it returns with no error code you're ok.

Then after creating it, you can hook Travis to your pull requests for adding new SVGs in the repo (I'm assuming the `master` branch is protected and can only receive new commits using a PR). In the Travis "build" you'll run the npm script you prepared.
If it fails it will block the merging of the PR (once you'll set it as a blocker in the branch settings of the repo) until you'll fix it.

That way you'll be 100% safe from any issues like this one.

I may have written it with much details, but it's really easy and Travis is 2 minutes to set up.

Does that make sense?

**Comment by allienworks** [comment]
> ..before you publish a new version of the package. At the moment this package is broken and we cannot use it.

Why do you keep talking about packages, when this is just a simple repo containing some SVG images and CSS files?

I get your idea, however I think it is redundantly complex. I have no experience with any of the tools you describe (Travis, branch protecting, building via npm, ..), I'll just set up a Gulp task to optimise those SVGs via `svgo` as you suggest, which should be sufficient.

Keep in mind I'm no programmer. If I was, I wouldn't probably be drawing icons, hehe.

**Comment by allienworks** [comment]
@kazazor OK, so it's been bugging me those last 2 hours or so, so I decided to give it a try anyways (learn new things, right?). Could you please point me in the direction of that

> npm building via `svgo`

I should use? As I said, I'm using Gulp, but I'm not sure it's the same thing as you suggest.. I'm a bit lost on what the script should contain and in which format. Is that just a bash script with
```
svgo -f ../path/to/folder/with/svg/files
```
?

**Comment by kazazor** [comment]
OK I see now the confusion and why I called it a package all the time. Have a look here: https://www.npmjs.com/package/cryptocoins-icons

This is an npm package that actually points to this repo as its repo. So it's a wrapper of this repo to be used in js projects.

It is just a shell script just like you mentioned in your comment.
If it will fail it means something is wrong with your SVGs

Now if you're using Gulp (and I haven't seen it in the repo here) I would say you can even do it simpler..

You can just have a `package.json` file in this repo with the content like this:
```js
{
  "name": "<your package name>",
  "version": "0.0.1",
  "scripts": {
    "test": "node_modules/.bin/svgo -f <path_to_folder>"
  },
  "devDependencies": {
    "svgo": "latest"
  }
```

Then just running `npm i` and then `npm test` will run your code. No need for complex Gulp here..

**Comment by allienworks** [comment]
Oh I see! Yeah, that guy asked me to publish my repo on NPM, so I gave him permission waaay back. I've asked him to take it down (as it isn't even up-to-date anymore).

I've already started to play with Travis and what you wrote. Gotta say, it's exciting. Looks like I figured it out in the end: https://github.com/allienworks/travis-test/pull/1

When I have some time, I'll implement it all in here as well.

Thanks much for your valuable input and nudging me in the right direction! Glad to learn this!

**Comment by kazazor** [comment]
Sure thing :)
By the wya, when you do get him to remove his package, could be nice if you'll publish one (super easy!) when you're updating your SVGs.. Very useful IMO

**Comment by allienworks** [comment]
Sure, thanks for your help!

**Comment by kazazor** [comment]
I would be happy to help set up it as an npm package if you need help :)
That will be super helpful to me and for every team that creates web apps with these icons :)

**Comment by allienworks** [comment]
The package is already under my control. From what I've read in NPM docs, updating packages in a manual process.

Is there a way to update the package each time a commit/PR is merged into master? If you could point me in the right direction, that would be amazing :)

**Comment by kazazor** [comment]
Well I would actually keep it manually.. I think it's a little bit too risky to do it automatically..
But if you want that I'm sure you can just check on Travis if it's running on `master` branch and only on that branch run `npm publish`. You'll need to provide an `.npmrc` file there which you'll need to see how to supply to Travis because you don't want it to be pushed to the repo for everyone to see..

I guess it's too much to do and doesn't worth it :)

How ever, I would add a `prepublishOnly` scrupt to your `package.json` file that will run `npm test`.
`npm test` should run `svgo` on all your files so in case of an error the publish would fail..

**Comment by kazazor** [comment]
Missing part from my last comment:
So publishing a package which is broken is not something I would recommend. It will really make people hate you haha.

This kind of settings will protect you from that situation.
By the way, I think the issue is fixed with the new version so this repo may be closed

**Comment by allienworks** [comment]
Yes, I released a new version today, along with NPM package. It should be all well.

Thanks really much for all the info and help! Appreciated!
Also hopefully Cryptocoins will help you in your efforts – I'll be really glad to hear what have you built with the icons!
