### ISSUE TITLE
Getting colors for SVG icons

### ISSUE THREAD

**Issue by kazazor** [allienworks/cryptocoins#57]
How can I add all the colors of the coins?
I didn't see anything written on that in the documentation..

**Comment by allienworks** [comment]
You would have to be a bit more specific.

If you want to use it on the web, you can either "extract" all SVGs into you code manually (or use some of the [scripts](https://stackoverflow.com/a/11978996) available for that), than control the color via CSS's `fill`, like this:

```
.btc { fill: black; }
.btc:hover { fill: orange; }
```

This way, you can include the `cryptocoins-colors.css` file and edit it how you please.

**Comment by kazazor** [comment]
So basically all I wanted is to get the icons with their default colors from this package.
I see now that all I need is to include the css file.

This is not that clear (IMO) from the docs.. I would make it a little bit clearer since this css file is only mentioned for the web fonts which is the old way of using this repo

**Comment by allienworks** [comment]
Thanks for pointing that out. I totally missed that when I moved the install instructions to Wiki. Fixed!
