### ISSUE TITLE
Use devDependencies instead of dependencies in the package.json file

### ISSUE THREAD

**Issue by kazazor** [allienworks/cryptocoins#59]
It looks like you have entered some of your internal tools (like `gulp`) to the dependencies section.
when installing your package it also installs everything in `dependencies`, but this is not needed.
What you wanted to do it use `devDependencies` so when you run `npm install` in the repo it will install it, but when installing in another project it will not installs these tools

**Comment by allienworks** [comment]
Fixed, thanks!
