### ISSUE TITLE
ZCash (ZEC)

### ISSUE THREAD

**Issue by simsketch** [allienworks/cryptocoins#60]
To request icons for your coin, please fill info below:

---

### Coin name (`TICKER`)

* link to logo: https://z.cash/theme/images/zcash-logo-gold.png
* official website: https://z.cash/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by buzztiaan** [comment]
https://github.com/allienworks/cryptocoins/blob/master/SVG/ZEC.svg

**Comment by simsketch** [comment]
ok thank you...heh...now i realize it's because i was looking at the demo...thanks very much!
