### ISSUE TITLE
alt.svg missing for several coins

### ISSUE THREAD

**Issue by meronym** [allienworks/cryptocoins#61]
GRS-alt.svg is missing from the repo, while GRS.svg is present. Same goes for: BTA.svg, DGD.svg, DGX.svg, GRS.svg

Is this due to the fact that the -alt version would have been visually identical to the normal version?

**Comment by allienworks** [comment]
> Is this due to the fact that the -alt version would have been visually identical to the normal version?

Yes. There are a few coins, to which it wouldn't make much sense to make any alternatives.
