### ISSUE TITLE
EOS Coin

### ISSUE THREAD

**Issue by jan10101** [allienworks/cryptocoins#62]
Hi,

I think it would be nice to add the EOS icon. It's already tradeable on bitfinex.

To request icons for your coin, please fill info below:

---

### Coin name (`TICKER`)

EOS Coin (EOS)

* link to logo: https://d340lr3764rrcr.cloudfront.net/Images/eos_logo@2x.png
* official website: https://eos.io/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
