### ISSUE TITLE
letter/keystroke mapping 

### ISSUE THREAD

**Issue by ksteigerwald** [allienworks/cryptocoins#64]
Please provide letter/key mapping for the fonts. Right now it is all class based. I will like to use these in an iOS app. Thanks!

-PS: Grabbed your CM font and shot you some lite.

**Comment by allienworks** [comment]
Hey @ksteigerwald,

thanks for the lite and CM; I appreciate that!

Regarding key mapping – I don't have that now. Not sure but mapping might even change everytime new icons is added (the whole webfont magic is handled by Gulp tasks), so I wouldn't even recommend building your app on mapping.

If possible, I'd use directly SVG icons, which would be probably the best way to include the icons in your app. Webfont is purely for web usage; it might produce unexpected results when used elsewhere.
