### ISSUE TITLE
MCO Mona.co Coin

### ISSUE THREAD

**Issue by ryanmaule** [allienworks/cryptocoins#65]
To request icons for your coin, please fill info below:

---

### Coin name (`MCO`)

* link to logo: https://www.mona.co/images/logo-white-ff8b4b8c.svg
* official website: https://www.mona.co/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
