### ISSUE TITLE
ANTSHARES / NEO

### ISSUE THREAD

**Issue by ryanmaule** [allienworks/cryptocoins#66]
To request icons for your coin, please fill info below:

---

### ANTSHARES / NEO (`NEO`) (ALSO ANS)

* link to logo: https://coinmarketcap.com/currencies/neo/
* official website: https://neo.org/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
