### ISSUE TITLE
Bitcoin Cash

### ISSUE THREAD

**Issue by RichyT** [allienworks/cryptocoins#67]
To request icons for your coin, please fill info below:

---

Bitcoin Cash (BCC/XBC, possibly BCH)

https://static.wixstatic.com/media/78da39_0211960888b44889967bc26def621b0a~mv2.png/v1/fill/w_250,h_154,al_c/78da39_0211960888b44889967bc26def621b0a~mv2.png
https://www.bitcoincash.org/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): f7931a
* bitcointalk.org thread: N/A

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by w96k** [comment]
Need that one too

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
