### ISSUE TITLE
webfont classes implemented with 'class="cc-BTC"' (with a hyphen, rather than a space)

### ISSUE THREAD

**Issue by dutu** [allienworks/cryptocoins#71]
The latest version of webfonts defines the classes beginning with `cc-` (with a hyphen, rather than a space),  e.g. `cc-BTC`.
Icon colors seem not to work anymore.

As per the note here https://labs.allienworks.net/icons/cryptocoins/ icons should be implemented via `class="cc BTC"` (with a space).

**Comment by allienworks** [comment]
Hi @dutu, thanks for info. The latest implementation of webfont generator has different config than the former one. Maintaining the webfont version is really a pain, there are many complications.. moreover the webfont generator broke again.

I'm trying to figure out a way how to solve all of those. So far, webfonts should be used with hyphen again. If you need, you can edit the CSS colors file manually (with hyphens), so it works again. Sorry for the trouble.

**Comment by dutu** [comment]
No problem. Thanks for your great work
