### ISSUE TITLE
Tezos

### ISSUE THREAD

**Issue by eugeneotto** [allienworks/cryptocoins#73]
To request icons for your coin, please fill info below:

---

### Coin name (`XTZ`)

* link to logo: https://www.tezos.com/static/T-Logo.svg (it's white)
* official website: https://www.tezos.com/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#FFFFFF`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=715818.0

Thank you!

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
