### ISSUE TITLE
There is no file called cryptocoins-icons.svg but referenced in \webfont\cryptocoins.css

### ISSUE THREAD

**Issue by syclone** [allienworks/cryptocoins#74]
There is no cryptocoins-icons.svg but referenced in \webfont\cryptocoins.css:

@font-face {
  font-family: "cryptocoins-icons";
  src: url('./cryptocoins-icons.eot');
  src: url('./cryptocoins-icons.eot?#iefix') format('eot'),
    url('./cryptocoins-icons.woff2') format('woff2'),   <-- HERE
    url('./cryptocoins-icons.woff') format('woff'),
    url('./cryptocoins-icons.ttf') format('truetype'),
    url('./cryptocoins-icons.svg#cryptocoins-icons') format('svg');   <-- HERE
}

Cause failed build for webpack mixins

**Comment by allienworks** [comment]
Sorry for this, it was my mistake when configuring automatic webfont generator. Will be fixed in next release (2.6), thanks for notice!

**Comment by syclone** [comment]
OK Great. Thanks!
