### ISSUE TITLE
Omise Go

### ISSUE THREAD

**Issue by sarunw** [allienworks/cryptocoins#75]
To request icons for your coin, please fill info below:

---

### Omise Go (`OMG`)

* link to logo: 
* official website: https://omg.omise.co/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#1A53F0`
* bitcointalk.org thread: https://bitcointalk.org/index.php?topic=2023054.0

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Hey, icon just added to the pack. [Donations](https://allien.work/donate) are appreciated!

Enjoy!
