### ISSUE TITLE
Request for icon Zcash

### ISSUE THREAD

**Issue by AdRock952** [allienworks/cryptocoins#77]
To request icons for your coin, please fill info below:

---

### Coin name (`TICKER`) Zcash

* link to logo: https://z.cash//theme/images/zcash-logo-gold.png
* official website:  https://z.cash/about.html

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment]
Zcash is [already](https://github.com/allienworks/cryptocoins/blob/master/SVG/ZEC.svg) [included](https://github.com/allienworks/cryptocoins/blob/master/SVG/ZEC-alt.svg).

Tips welcome! ZEC: `t1ctf7yjtSGAjSH9EUncfDQkcn8mvCWXjkX`
