### ISSUE TITLE
How to increase the icon sizes?

### ISSUE THREAD

**Issue by Nixtren** [allienworks/cryptocoins#8]
Hello,

First of all, I'm a CSS noob, so I apologize if this is a basic question. 

Font Awesome has a class to increase icon sizes, e.g.:
`<i class="fa fa-camera-retro fa-4x"></i> fa-4x`
https://fortawesome.github.io/Font-Awesome/examples/

Is there any kind of "fa-2x" or "fa-4x" and etc. for Cryptocoin icons? If not, how can I achieve the same result using CSS?

Thanks for any help in advance.

**Comment by allienworks** [comment]
Hi @Nixtren,

no need for apologies, I'm here to help ;) I haven't included those "size modifiers" (or how to call them), but you can easily control icon size by defining it's font size (after all, it's basically just text).

e.g. let's say we want our Bitcoin icon big – so let's define it's size by "font-size" like that:

```
i.cc-BTC { font-size: 100px; }
```

If you're using multiple icons on more places and want to resize all of them (or just portion), add some class to them (like ```<i class="cc-BTC x2"></i>```) and then define the rules in CSS:

```
i.x2 { font-size: 100px; }
```

Did that answered your question sufficiently or do you need some more help? :)

**Comment by Nixtren** [comment]
You're awesome @allienworks, thanks ;D

**Comment by allienworks** [comment]
You're welcome @Nixtren!
