### ISSUE TITLE
Normalize symbol names?

### ISSUE THREAD

**Issue by knoopx** [allienworks/cryptocoins#81]
Bitcoin Cash symbol BCH is more widely used than than BCC, can I suggest to follow to https://coinmarketcap.com/ as reference for coin symbols?

**Comment by msembinelli** [comment]
I agree that bitcoin cash should probably use BCH.
BCC is the ticker for bitconnect.

I have made a PR fixing this: https://github.com/allienworks/cryptocoins/pull/89
