### ISSUE TITLE
Quantum

### ISSUE THREAD

**Issue by jaewoonglee** [allienworks/cryptocoins#82]
### Quantum (`QTUM`)

* link to logo: https://www.cryptoninjas.net/wp-content/uploads/2017/03/qtum.png
* official website: https://www.quantumproject.org/

It is one of popular cryptocurrency
Thanks!

**Comment by allienworks** [comment]
I'm a bit confused. The logo you sent me doesn't match the one on the website.. so which is it?

**Comment by jaewoonglee** [comment]
I think so, too.
official quantum homepage not using the attached logo. but some major
exchanges using that.
It seems more common to use the attached logo. :)
and.. nowadays, it is very hot currency.

**Comment by allienworks** [comment]
Note to self: the website you posted seems to be related to completely different project.
