### ISSUE TITLE
Some icons missing width & height attributes

### ISSUE THREAD

**Issue by altherat** [allienworks/cryptocoins#84]
Most icons have width and height attributes, but some ([IOTA-alt](https://raw.githubusercontent.com/allienworks/cryptocoins/master/SVG/IOTA-alt.svg) for example) do not. 

I'm using an [SVG rendering library in android](https://github.com/BigBadaboom/androidsvg), and the lack of width/height attributes is causing some problems.

**Comment by allienworks** [comment]
Could you please list all the icons missing the height attributes?
Or maybe if you have time even fix those ones you know of?

**Comment by chrislennon** [comment]
I ran into this issue too, for my use case adding `width="226.8" height="226.8"` to the coins `IOTA-alt.svg` & `ETC-alt.svg` seemed to correct it.

Using the command `grep -rL width .` inside `/SVG` seems to show the effected icons, listed below.

I will try a PR, hoping I can mass search and replace this 😜 

```
./ADC-alt.svg
./ADC.svg
./BAT-alt.svg
./BAT.svg
./BRK-alt.svg
./BRK.svg
./BRX-alt.svg
./BRX.svg
./BSD-alt.svg
./BSD.svg
./DAO-alt.svg
./DAO.svg
./ERC-alt.svg
./ERC.svg
./ETC-alt.svg
./ETC.svg
./FLO-alt.svg
./FLO.svg
./GLD-alt.svg
./GLD.svg
./GNO-alt.svg
./GNO.svg
./GNT-alt.svg
./GNT.svg
./GRS.svg
./HEAT-alt.svg
./HEAT.svg
./ICN-alt.svg
./ICN.svg
./INCNT-alt.svg
./INCNT.svg
./IOTA-alt.svg
./IOTA.svg
./KMD-alt.svg
./KMD.svg
./KOBO.svg
./LBC-alt.svg
./LBC.svg
./PINK-alt.svg
./PINK.svg
./PIVX-alt.svg
./PIVX.svg
./PPC-alt.svg
./PPC.svg
./RADS-alt.svg
./RADS.svg
./RDD-alt.svg
./RDD.svg
./RISE-alt.svg
./RISE.svg
./SIA-alt.svg
./SIA.svg
./SLS-alt.svg
./SLS.svg
./SNRG-alt.svg
./SNRG.svg
./STEEM-alt.svg
./STEEM.svg
./SWIFT-alt.svg
./SWIFT.svg
./TRIG-alt.svg
./TRIG.svg
./UBQ-alt.svg
./UBQ.svg
```

**Comment by chrislennon** [comment]
PR #126 now covers this change - given the size of the changes, please double check it 😅
