### ISSUE TITLE
The DAO icons

### ISSUE THREAD

**Issue by EvgeniyPolovniy** [allienworks/cryptocoins#9]
Do you plan to add icon The DAO?

**Comment by EvgeniyPolovniy** [comment]
Yes, it's this site.

**Comment by allienworks** [comment]
Kk, noted. I'll let you know as soon as it's out.

Btw from what I see, the DAO's logo is _really_ close to Dogecoin's.. I guess the only difference there will be the square..

**Comment by allienworks** [comment]
@EvgeniyPolovniy finally released with DAO included ;)
